# New main script for Monotonicity analysis generation
# 29/5/2014

##### TO DO
# 1) Look again at calculation of covariance approaches



##############################


rm(list=ls())

# Load prerequisites

source("scripts/LoadPackages.R")

RequiredPackages(
    c(
        "MASS",
        "xlsx",
        "ggplot2",
        "reshape",
        "gdata",
        "devtools",
        "plyr"
        )
    )

#######################################################################################################
######################### FUNCTIONS ###################################################################
#######################################################################################################
source("scripts/functions.r")


#######################################################################################################
######################### GLOBAL VARIABLES ############################################################
#######################################################################################################
# Global variables will be ALL UPPERCASE to distinguish them from other variables

N_PSA <- 10000

# The following parameter should be set to TRUE if you want various calibration parameters
# generated by implementing various methods to be 'thrown' while the methods are being 
# implemented then 'caught' by an object called 'sponge'
THROW_FACTS <- FALSE 

if (THROW_FACTS) sponge <- c()

#######################################################################################################
######################### MAIN SECTION ############################################################
#######################################################################################################


source("Scripts/manage_data.r")



####
source("scripts/make_summaries_dataframes.r")

source("scripts/Make_Figures.R")



